### ISSUE TITLE
Can't upload videos

### ISSUE THREAD

**Issue by hertzel-kuriel** [YU-MITC/moodle-local_yumymedia#1]
Hi
We installed Kaltura CE 16.14 server and using YU Kaltura plugins 2021051700.
We set the configuration page properly with:
1- server name, user and admin who can access the Kaltura server as an admin
2- Players list are shown
3- Both Kaltura ad Moodle are using HTTPs 

When we try to upload a file from local disk or by recording using the plugin, we get 3 error messages:
1- Could not connect to the Kaltura server
2- Resource not found https://Moodle_Server_Name/local/yumymedia/undefined/api_v3/service/uploadToken/action/delete
3- Resource not found
[Kaltura_Server_Address/api_v3/service/uploadToken/action/add?ks=YjViNzZkODgxNjEzYWZmMzk2ODg4MjIyNWExMTdmYjM2NDljYzdkYnwtMjstMjsxNjU3NDgyMTQzOzI7MTY1NzQ2MDU0My4wNzgzO2dhbmVzaDRvbmdyYXBoQGdtYWlsLmNvbTs7Ow==&uploadToken:objectType=KalturaUploadTokenuploadToken:fileName=ACNE%20ZoomVid%20Alon%203.mp4&uploadToken:fileSize=4489384&uploadToken:autoFinalize=-1&_=1657460566679](https://demoen14.learningzone.me/local/yumymedia/kaltura.learningzone.me/api_v3/service/uploadToken/action/add?ks=YjViNzZkODgxNjEzYWZmMzk2ODg4MjIyNWExMTdmYjM2NDljYzdkYnwtMjstMjsxNjU3NDgyMTQzOzI7MTY1NzQ2MDU0My4wNzgzO2dhbmVzaDRvbmdyYXBoQGdtYWlsLmNvbTs7Ow==&uploadToken:objectType=KalturaUploadTokenuploadToken:fileName=ACNE%20ZoomVid%20Alon%203.mp4&uploadToken:fileSize=4489384&uploadToken:autoFinalize=-1&_=1657460566679)

Any assistance will be appreciated.
Thanks in advance

Hertzel

**Comment by YU-MITC** [comment]
Hello,

For integration between the Moodle and Kaltura, you must use Kaltura's "Publisher" account is not system administrator.
And, in your system, "lcoal_yumymedia" plugin try to use APIs on your Moodle server.
But, APIs are stored in your Kaltura server.
Please confirm "Server URI", "Hosted account login", and "Hosted account password" settings in plugin's setting page.
"Server URI" is URL of your Kaltura server.
"Hosted account login" and "Hosted account password" are username and password respectively, for your publisher account.

Regards,

**Comment by hertzel-kuriel** [comment]
Hi
Thanks for your response.
I changed the user and password to the Publisher's user and password, but the problem remains. It still cannot connect to the server.
I am not sure i understood your following comment:
*And, in your system, "lcoal_yumymedia" plugin try to use APIs on your Moodle server.
But, APIs are stored in your Kaltura server.*

Would you mind elaborating on that?

**Comment by YU-MITC** [comment]
We paid attention to the access behavior to the following URL.

https://Moodle_Server_Name/local/yumymedia/undefined/api_v3/service/uploadToken/action/delete

In our plugins, "local_yukaltura" has the Kaltura Client libraries, and "local_yumymedia" uses the libraries.
The libraries invoke Kaltura's API works as Web API (CGI) on your Kaltura server.
Therefore, if the plugin and the Kaltura server can connect successfully, the plugin will access the following URL.

https://Kaltura_Server_Address/api_v3/service/uploadToken/action/delete

Currently, we do not know the cause of such a malfunction.
We believe that investigating what causes the plugin to access the wrong URL is a hint to fix this issue.

**Comment by hertzel-kuriel** [comment]
Hi,
After spending some time we were able to reach a point where the Kaltura server works OK and we are able to upload content from Moodle to Kaltura using the plugin.
We are now facing a new issue related to playing uploaded videos in Moodle.
After the video is uploaded and processed on the Kaltura server side when we access the course and access the Media activity, we get the attached error message

![image](https://user-images.githubusercontent.com/56868036/181598000-ddaa7d60-9972-4af4-8ea6-1486e1285bb2.png)

If we take the embed code of the video from the Kaltura server and embed it into Moodle, we video plays just fine.

To us, it indicates that there might be an issue related to the player that comes with the plugin.
We noticed that the HTML version used when the video play on Kaltura server is 2.8.5 and the HTML player version used by the YU plugin is 1.8.8.

Is there an issue here we should be aware of or are we missing something?
Thanks,

**Comment by YU-MITC** [comment]
Our plugins do not have any video player.
So that, you should create your own video player on your Kaltura Management Console (KMC).
And, please choose your video player at plugin's setting page on your Moodle site.
Please create a video resource instance again in your Moodle course, after setting of the video player.

Regards,

**Comment by hertzel-kuriel** [comment]
Got it - Thanks!
It did the trick and it is all working now.

**Comment by YU-MITC** [comment]
We are happy to see this plugin working with your Moodle site.
